---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart RAB audit timer
  ansible.builtin.systemd_service:
    name: rab-audit.timer
    state: restarted
    daemon_reload: true

- name: Reload RAB LAN proxy
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
  when: rab_api_lan_enabled
